### ISSUE TITLE
Does the program return the amount of slime chunks found or not?

### ISSUE THREAD

**Issue by MasterGaro** [Nukelawe/slimefinder#10]
I've been running this program trying to find at least 54 slime chunks within a despawn sphere, but everytime a new image is generated from the program I can't see to figure out how many slimechunks it found; I did spot a number that similar in every single name of the file: 31c222 < --- Example

Not sure if this number determines the amount of slime chunks that it has found, But I am wondering how I would check

**Comment by Nukelawe** [comment]
31/222 means that the chunk mask that was used in your search consists of 222 chunks, and that for this particular cluster 31 of them are slime. So, the program does indeed return the number of slime chunks in the results csv-file. However, the size is returned only for those positions that match the search criteria. For example, if your search criteria require that chunk-size > 50, then any results such as 31/222 would be excluded as they do not meet the criteria. When thinking about the criteria, keep mind mind that there is an OR-relationship between chunk and block size criteria.
