### ISSUE TITLE
Slime Chunk Formula Error

### ISSUE THREAD

**Issue by cnie109** [Nukelawe/slimefinder#13]
It seems that the formula for determining whether a chunk is a slime chunk is incorrect. I don't know what the error is, but when I replaced what is currently in the code with what is found on the Minecraft wiki, the results were correct. It may be that the constants are wrong, or that casting to a long instead of an int breaks it, but it doesn't produce accurate results when I use it as is.

Link to wiki: https://minecraft.wiki/w/Slime#%22Slime_chunks%22

**Comment by Boobies** [comment]
And did you first rule out whether the wiki was wrong?

**Comment by cnie109** [comment]
Yes. I checked the coordinates in game with the current implementation, and it was incorrect. However, when I used the formula on the wiki, the slime chunk patterns were correct.

**Comment by Boobies** [comment]
I checked the game code, the wiki, and the slimefinder code and they all seem to agree precisely on the formula. I cannot test to say for sure whether there's a bug somewhere else but I somehow doubt it. I can't do a test right now but if you have a case where you get wrong results, can you please provide it? I could look into it tomorrow and submit a PR.

**Comment by cnie109** [comment]
There is one difference. The formula on the wiki casts the values to ints, while the formula in the slime finder casts to longs. This is probably resulting in some issues with the widening and narrowing that normally happens in it, causing some discrepancies. Tomorrow I'll be able to supply an example

**Comment by cnie109** [comment]
I've just gone to get an example of it, but then I couldn't replicate it. I have no idea why, and I don't know why it didn't work for me months ago. Sorry for wasting your time.
